# Generated by Django 4.2.5 on 2023-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_blogdatabase_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdatabase',
            options={'ordering': ('started',)},
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='author',
            new_name='brew_master',
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='title',
            new_name='brewery_branch',
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='body',
            new_name='extra_ingredients',
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='publish',
            new_name='started',
        ),
        migrations.RemoveField(
            model_name='blogdatabase',
            name='status',
        ),
        migrations.AddField(
            model_name='blogdatabase',
            name='molt_quantity',
            field=models.CharField(choices=[('Level 1', '40ml'), ('Level 2', '80ml'), ('Level 3', '180ml')], default='Level 1', max_length=10),
        ),
        migrations.AddField(
            model_name='blogdatabase',
            name='sorgum_quantity',
            field=models.CharField(choices=[('Level 1', '40kg'), ('Level 2', '80kg'), ('Level 3', '180kg')], default='Level 1', max_length=10),
        ),
    ]
