# Generated by Django 4.2.5 on 2023-10-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_blogdatabase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdatabase',
            options={'ordering': ('publish',)},
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='brew_master',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='extra_ingredients',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='started',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='blogdatabase',
            old_name='brewery_branch',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogdatabase',
            name='molt_quantity',
        ),
        migrations.RemoveField(
            model_name='blogdatabase',
            name='sorgum_quantity',
        ),
        migrations.AddField(
            model_name='blogdatabase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
