# Generated by Django 4.2.5 on 2023-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_blogdatabase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdatabase',
            options={'ordering': ('-publish',)},
        ),
    ]
