# Generated by Django 4.2.5 on 2023-11-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_blogdatabase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogdatabase',
            managers=[
            ],
        ),
    ]
